---
- name: Pull docker image of backend
  hosts: all
  tasks:
    - name: Pull image
      docker_image:
        name: vtandonv/communityhubbackend
        source: pull
     
     - name: Create back-end container
       docker_container: 
        name: springboot-con1
        image: vtandonv/communityhubbackend
        ports:
          - "8090:8090"
        
      
